export const actions = {
    UPDATE_FLIGHT_SEARCH_PREFERENCES: 'UPDATE_FLIGHT_SEARCH_PREFERENCES',
    UPDATE_AIRLINES : 'UPDATE_AIRLINES',
    UPDATE_FLIGHTS: 'UPDATE_FLIGHTS',
    UPDATE_PASSENGER_INFORMATION : 'UPDATE_PASSENGER_INFORMATION',  
}